<?php
/**
 * Created by PhpStorm.
 * User: ebortnik
 * Date: 28.12.2018
 * Time: 15:50
 */

class ManagersController extends Zend_Controller_Action
{
    public function init()
    {
        parent::init(); // TODO: Change the autogenerated stub
    }

    public function indexAction(){
        $this->view->title = "Managers list";
        $this->view->headTitle($this->view->title);

        $manager = new Application_Model_Manager();
        $this->view->managers = $manager->getAllManagers();
    }

    public function addAction(){
        $this->view->title = "Add new manager";
        $this->view->headTitle($this->view->title);

        $form = new Application_Form_Manager();

        if ($this->getRequest()->isPost()){
            if ($form->isValid($this->getRequest()->getPost())){
                $manager = new Application_Model_Manager();
                $manager->fill($form->getValues());
                $manager->save();
                $this->_helper->redirector('index');
            }
        }

        $this->view->form = $form;
    }

    public function deleteAction(){
        $id = $this->_getParam('id');
        $customer = new Application_Model_Manager($id);
        $customer->delete();
        $this->_helper->redirector('index');
    }

    public function viewAction(){
        $this->view->title = "manager data";
        $this->view->headTitle($this->view->title);

    }

//    public function editAction(){
//        $this->view->title = "Add task to customer";
//        $this->view->headTitle($this->view->title);
//    }
}