<?php echo $this->doctype('HTML5'); ?>
<html xmlns="http://www.w3.org/1999/xhtml">

<head>
    <?php echo $this->headMeta();
    echo $this->headTitle();
    $this->headLink()->prependStylesheet('/css/main.css');
    $this->headLink()->appendStylesheet(
        $this->baseUrl() . '/css/blueprint/screen.css', 'screen');
    $this->headLink()->appendStylesheet(
        $this->baseUrl() . '/css/blueprint/print.css', 'print');
    echo $this->headLink(); ?>
</head>

<body>
<div class="container">
    <div id="header" class="span-24 last">
        <h2><?php echo $this->title;?></h2>
    </div>
    <div id="content" class="span-17 colborder"><?php echo $this->layout()->content; ?></div>
    <div id="sidebar" class="spaan-6 last">
        <p>sidebar</p>
    </div>
    <div id="footer" class="span-24 last">Footer</div>
</div>
</body>

</html>
